### ISSUE TITLE
Null pointer exception problem(email-class-implementation branch)

### ISSUE THREAD

**Issue by Strafo** [AlessandroCaroti/ACSprogetto#20]
Testando con i tester;ServerTest e ClientTest_2 dopo essersi connesso efficamente il client cerca di fare la register invocando il metodo della classe Client.java register()
```

/**
     *Il client si registra sul server su cui si era connesso con il metodo connect() e viene settato il cookie
     * @return true se registrazione andata a buon fine, false altrimenti
     */
    @Override
    public boolean register() {
        if(server_stub==null){System.err.println("ciao");}//TODO DA ELIMINARE --->lo stub non viene settato
        try {
            ResponseCode responseCode = server_stub.register(this.username, this.plainPassword, this.skeleton, this.myPublicKey,"emailTest@qualcosa.org");
            return registered(responseCode);
        }catch (RemoteException e){
            errorStamp(e, "Unable to reach the server.");
            return false;
        }
    }
```

Quando chiama server_stub.register(this.username.....) lancia l'eccezione nullpointer
Dalla linea aggiunta  if(server_stub==null){System.err.println("ciao") per il profiling ho notato che server_stub non viene settato.
Ho provato cambiando le visibilità dei fields (di anonymousAccount) da private a protected ma la situazione non è cambiata. Idee? Non so come orientarmi tra i file Infoprovider ecc

**Comment by AlessandroCaroti** [comment]
ti scrivo su slack
