### ISSUE TITLE
TimeOut durante la registrazione

### ISSUE THREAD

**Issue by AlessandroCaroti** [AlessandroCaroti/ACSprogetto#22]
Non so se ci hai già pensato o se sia fattibile però durante registrazione quando si fa la richiesta del codice passato via email non sarebbe male imporre un TimeOut , tipo se il client non risponde dopo un tot di tempo la registrazione fallisce.

**Comment by AlessandroCaroti** [comment]
Ho trovato qualcosa ma non so se sia adatta a quello che pensavo
[https://stackoverflow.com/questions/1822695/java-rmi-client-timeout/1822717#1822717](url)

**Comment by Strafo** [comment]
Dopo il testing del branch corrente e dopo il merge di quest'ultimo provo su uno nuovo

**Comment by Strafo** [comment]
direi che possiamo chiudere questa issue lol
