### ISSUE TITLE
Possibile mal funzionamento nel sistema publish-notify

### ISSUE THREAD

**Issue by AlessandroCaroti** [AlessandroCaroti/ACSprogetto#30]
Ora come ora un client può inviare un messaggio su un Topic a cui non è ancora inscritto continuando ad non essere iscritto a quel Topic e non so se lasciarlo così o forzare il fatto che appena invii un messaggio ad un certo topic ti ci iscrivi automaticamente.

Che facciamo?

**Comment by Strafo** [comment]
Lascia così per ora...
Cerchiamo di concludere la cosa.
Abbiamo già fatto più del dovuto direi
